version: '3'

services:

  nginx:
    build:
      context: enerknol
      dockerfile: Dockerfile-nginx
    links:
      - enerknol:enerknol
    ports:
      - ${PORT}:80

  enerknol:
    build:
      context: enerknol
      dockerfile: Dockerfile-flask
    links:
      - elastic:elastic
      - mongo:mongo
      - mysql:mysql
    environment:
      - FLASK_CONFIG_SQLALCHEMY_DATABASE_URI=mysql+cymysql://enerknol:enerknol@mysql:3306/enerknol?charset=utf8
      - FLASK_CONFIG_MONGO_DATABASE_URI=mongodb://mongo:27017/enerknol
      - FLASK_CONFIG_ELASTIC_URI=http://elastic:9200
    ports:
      - 5000:80

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=enerknol
      - MYSQL_USER=enerknol
      - MYSQL_PASSWORD=enerknol
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 3306:3306
