version: '3'

services:

  nginx:
    build:
      context: search_app
      dockerfile: Dockerfile-nginx
    links:
      - search_app:search_app
    ports:
      - ${PORT}:80

  search_app:
    build:
      context: search_app
      dockerfile: Dockerfile-flask
    links:
      - elastic:elastic
      - mongo:mongo
      - mysql:mysql
    environment:
      - FLASK_CONFIG_DEBUG=${FLASK_CONFIG_DEBUG}
      - FLASK_CONFIG_TESTING=${FLASK_CONFIG_TESTING}
      - FLASK_CONFIG_PASSWORD_SALT=${FLASK_CONFIG_PASSWORD_SALT}
      - FLASK_CONFIG_SECRET_KEY=${FLASK_CONFIG_SECRET_KEY}
      - FLASK_CONFIG_SQLALCHEMY_DATABASE_URI=mysql+cymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/search_app?charset=utf8
      - FLASK_CONFIG_MONGO_DATABASE_URI=mongodb://mongo:27017/search_app
      - FLASK_CONFIG_ELASTIC_URI=http://elastic:9200
    ports:
      - 5000:80

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=search_app
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
