FROM python:3.6

ADD requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

ADD search_app/ /app/search_app

WORKDIR /app

ENV FLASK_CONFIG_DEBUG=""
ENV FLASK_CONFIG_TESTING=""
ENV FLASK_CONFIG_SQLALCHEMY_DATABASE_URI=""
ENV FLASK_CONFIG_MONGO_DATABASE_URI=""
ENV FLASK_CONFIG_ELASTIC_URI=""
ENV FLASK_CONFIG_PASSWORD_SALT=""
ENV FLASK_CONFIG_SECRET_KEY=""

CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0:80", "--log-level=debug", "search_app.app:app"]

EXPOSE 80
