FROM python:3.6

ADD requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

ADD enerknol/ /app/enerknol

WORKDIR /app

ENV FLASK_CONFIG_DEBUG=""
ENV FLASK_CONFIG_SQLALCHEMY_DATABASE_URI=""
ENV FLASK_CONFIG_PASSWORD_SALT=""
ENV FLASK_CONFIG_SECRET_KEY=""

CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0:80", "--log-level=debug", "enerknol.app:app"]

EXPOSE 80
