FROM python:3.6

ADD requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

ADD enerknol/ /app/enerknol

WORKDIR /app

ENV FLASK_CONFIG_DEBUG="True"
ENV FLASK_CONFIG_SQLALCHEMY_DATABASE_URI="sqlite:////app/test.db"
ENV FLASK_CONFIG_PASSWORD_SALT="changeme-salt"
ENV FLASK_CONFIG_SECRET_KEY="changeme-secret-key"

CMD ["gunicorn", "--workers=2", "--bind=0.0.0.0:80", "--log-level=debug", "enerknol.app:app"]

EXPOSE 80
